services:
  Cards:
    image: khrafaayke/cards
    ports:
      - "8085:8085"
    networks:
      - bank-network
  Accounttest:
    image: khrafaayke/accounttest
    ports:
      - "8089:8089"
    networks:
      - bank-network
  loan:
    image: khrafaayke/loan
    ports:
      - "8084:8084"
    networks:
      - bank-network
  insurance:
    image: khrafaayke/loan
    ports:
      - "8071:8071"
    networks:
      - bank-network    
      
      
      
      
      
      
      
networks:
  bank-network: {}